Repository SEP-proj/AI, pull requests merged in 2023-09, with the labels that each got.

#2 fix: 1. 링크 제공 시 뉴스, 유튜브 제외하는 조건 추가 2. 링크 최대 3개 제공
  utils/search_google.py
Labels: 🐞BugFix

#5 make_question 말투 업데이트
  domain/chatbot.py
Labels: 🌟Feature

#7 check_content 업데이트
  domain/modification.py
Labels: 🌟Feature

#8 check_content 업데이트
  domain/modification.py
Labels: 🌟Feature

#10 Blessian
  .gitignore
  resource/model/openai_llms.py
Labels: 🐞BugFix

#13 fix: change return format
  domain/chatbot.py
  domain/topic_recommend.py
  resource/model/openai_llms.py
  utils/search_google.py
Labels: 🐞BugFix

#16 update: json키값 수정
  domain/chatbot.py
Labels: 🏗️Refactoring

#18 update: chage return format
  domain/chatbot.py
  utils/search_google.py
Labels: 🏗️Refactoring

#22 Modify check_content function pine-tuning prompt
  domain/modification.py
Labels: 🏗️Refactoring

#23 modified prompt
  domain/modification.py
  resource/model/trending_topic.csv
Labels: 🏗️Refactoring

#25 최신 이슈 추가
  domain/topic_recommend.py
  resource/model/bard_hotissue.py
  resource/model/trending_topic.csv
Labels: 🌟Feature

#26 최신 이슈 반영 업데이트
  domain/topic_recommend.py
  resource/model/bard_hotissue.py
  resource/model/trending_topic.csv
Labels: 🏗️Refactoring

#28 feat: connect DB(sqlite)
  .gitignore
  alembic.ini
  database/models.py
  database/sqlite.py
  domain/chatbot.py
  domain/modification.py
  domain/topic_recommend.py
  main.py
  meta_training.db
  resource/model/openai_llms.py
  utils/make_chatbot.py
Labels: 🌟Feature

#29 merge 문제 해결
  domain/chatbot.py
  resource/model/openai_llms.py
  utils/make_chatbot.py
Labels: 🏗️Refactoring

#30 자유대화 langchain 적용 및 DB 등록
  .gitignore
  domain/chatbot.py
  meta_training.db
  resource/model/openai_llms.py
Labels: 🏗️Refactoring
